# #####################################################################
# Automatically generated by qmake (2.01a) Wed Oct 7 14:44:11 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += reader.h
SOURCES += main.cpp \
    reader.cpp
RESOURCES += pp.qrc
FORMS += dialog.ui
