#!/bin/bash          

# suppose you have all the qt-doc pages in QT_DOC_PATH
QT_DOC_PATH="$HOME/.vim/doc.trolltech.com/4.6/" #adjust to your own case
cd $QT_DOC_PATH
kw=$1".html" #concating two string is easy
name=$(ls|grep -i $kw) #no space is allowed between "name" and "="
echo --------
echo $name

lynx $name

###########   vim setting #############################
#
# so I finally have this in my .vimrc
# map <F12> :!qref <cword><ENTER>
# 
################################################
